# @package _global_

defaults:
  - _self_
#  - job

# Павраметры модели
seed: 44
sigma: 1
num_steps: 10
net_name: mlp_large
activation_fn: torch.nn.SiLU
model_name: dsbm
first_coupling: ref
inner_iters: 10
outer_iters: 3000
fb_sequence: ['b','f']
lr: 1e-5
batch_size: 64

# Параметры распределений
Gaussian_distribution:

  dataset_size: 1000
  test_dataset_size: 1000
  mean_1: 0.1
  var_1: 1
  
  mean_2: -0.1
  var_2: 1

  dim: 5

# Имя эксперимента
paths: 
  experiments_dir_name: gaussian_experiment
  