# @package _global_

defaults:
  - _self_
#  - job

# Павраметры модели
seed: 44
sigma: 0.3
num_steps: 10
net_name: mlp_large
activation_fn: torch.nn.SiLU
model_name: dsbm
first_coupling: ref
inner_iters: 10
outer_iters: 2000
fb_sequence: ['b','f']
lr: 1e-4
batch_size: 64

# Параметры распределений
Gaussian_distribution:

  dataset_size: 1000
  test_dataset_size: 1000
  mean_1: 0.5
  var_1: 0.01
  
  mean_2: -0.5
  var_2: 0.01

  dim: 5

# Имя эксперимента
paths: 
  experiments_dir_name: gaussian_experiment
  