# @package _global_

defaults:
  - _self_
  
dataset_name: gaussian
model_name: DSBM
seed: 42


# Model params
sigma: 1 
num_steps: 200
net_hidden_layer_width: 64
activation_fn: torch.nn.SiLU
batch_size: 128

# Train params
first_coupling: ref
inner_iters: 100
fb_sequence: ['b','f']


# Параметры датасета
dataset_size: 10000
test_dataset_size: 10000

dim: 5

x0_mean: [-1]
x0_vars_diag: [1]
x0_cov_pairs: []


x1_mean: [1]
x1_vars_diag: [1]
x1_cov_pairs: []

paths:
  experiments_dir_name: gaussian_dim=5_а=1_var=1_hlw=128_EXP